apiVersion: v1
kind: ReplicationController
metadata:
  name: myrc1
spec:
  replicas: 3
  selector: 
      env: dev1
  template: 
    metadata: 
       name: rcpods1
       labels:
         env: dev1
         node: minikube1
    spec:
     containers:
       - name: podrc1
         image: httpd
       
